#!/bin/bash -e

# Author: James Seiters
# Created: 2018/11/30
# Updated: 2018/12/3
# Copyright: GPLv3
# Description: A shell script to automate the creation of ZFS backed VM disk.
#						  Created from instructions on https://ramsdenj.com/2016/07/21/
#						  making-a-zvol-backed-virtualbox-vm-on-linux.html
#						  This is executed in the chroot environment.

err_report() {
	echo "Error on line $1"
}
trap 'err_report $LINENO' ERR

# Define internal variables.
linespacer=$(printf '*%.0s' {1..20})

# Configure the environment.
echo -e "$linespacer"
echo -e "\nConfiguring chroot."
echo -e "\n$linespacer\n"
ln -s /proc/self/mounts /etc/mtab

# Configure packages already installed.
echo -e "\nConfiguring locale."
# The only way I could get this to work is by removing the locales package first.
# Otherwise the dreaded:
# *** update-locale: Error: invalid locale settings:  LANG=en_US.UTF-8
# would appear.
apt purge --yes locales
echo "locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8" | debconf-set-selections
echo "locales locales/default_environment_locale select en_US.UTF-8" | debconf-set-selections
apt install --yes locales

echo -e "\nConfiguring timezone."
echo "tzdata tzdata/Areas select America" | debconf-set-selections
echo "tzdata tzdata/Zones/America select New_York" | debconf-set-selections
echo "tzdata tzdata/Zones/Etc select UTC" | debconf-set-selections
DEBIAN_FRONTEND=noninteractive dpkg-reconfigure tzdata

# Install new packages.
echo -e "\nInstalling packages."
apt update
apt install --yes --no-install-recommends linux-image-generic
apt install --yes nano network-manager zfs-initramfs
#echo "grub-pc grub2/linux_cmdline_default string " | debconf-set-selections
# Does not appaer to work.
#echo "grub-pc grub-pc/hidden_timeout boolean true" | debconf-set-selections
echo "grub-pc grub-pc/install_devices multiselect $DISK1, $DISK2" | debconf-set-selections
DEBIAN_FRONTEND=noninteractive apt install --yes grub-pc

# Add users and groups.
echo -e "\nAdding users and groups.\n"
addgroup --system lpadmin
addgroup --system sambashare
useradd $USERNAME -s /bin/bash -m -G sudo
echo "$USERNAME:$PASSWORD" | chpasswd
chage -d 0 $USERNAME

# Fix filesystem mount ordering.
echo -e "\nFixing filesystem mount ordering.\n"
zfs set mountpoint=legacy $POOLNAME/var/log
zfs set mountpoint=legacy $POOLNAME/var/tmp
zfs set mountpoint=legacy $POOLNAME/tmp
echo -e "$POOLNAME/var/log /var/log zfs relatime,nodev,noexec,nosuid 0 0\n$POOLNAME/var/tmp /var/tmp zfs relatime,nodev,nosuid 0 0\n$POOLNAME/tmp /tmp zfs relatime,nodev,nosuid 0 0\n" >> /etc/fstab

# Install grub
echo -e "\nUpdating grub configuration.\n"
update-initramfs -u -k all
sed -i 's/GRUB_TIMEOUT_STYLE=hidden/#GRUB_TIMEOUT_STYLE=hidden/g; s/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/GRUB_CMDLINE_LINUX_DEFAULT=""/g; s/#GRUB_TERMINAL=console/GRUB_TERMINAL=console/g;' /etc/default/grub
update-grub

# Prepare for reboot.
echo -e "\nCreating snapshot."
zfs snapshot $POOLNAME/ROOT/OS@install
